export const FETCH_VIJESTIZSPORTA_REQUEST = 'FETCH_VIJESTIZSPORTA_REQUEST';
export const FETCH_VIJESTIZSPORTA_SUCCESS = 'FETCH_VIJESTIZSPORTA_SUCCESS';
export const FETCH_VIJESTIZSPORTA_FAILURE = 'FETCH_VIJESTIZSPORTA_FAILURE';