export const FETCH_SVIJETBICIKLIZMA_REQUEST = 'FETCH_SVIJETBICIKLIZMA_REQUEST';
export const FETCH_SVIJETBICIKLIZMA_SUCCESS = 'FETCH_SVIJETBICIKLIZMA_SUCCESS';
export const FETCH_SVIJETBICIKLIZMA_FAILURE = 'FETCH_SVIJETBICIKLIZMA_FAILURE';