export const FETCH_PONUDAUPRODAVNICAMA_REQUEST = 'FETCH_PONUDAUPRODAVNICAMA_REQUEST';
export const FETCH_PONUDAUPRODAVNICAMA_SUCCESS = 'FETCH_PONUDAUPRODAVNICAMA_SUCCESS';
export const FETCH_PONUDAUPRODAVNICAMA_FAILURE = 'FETCH_PONUDAUPRODAVNICAMA_FAILURE';