export const FETCH_PRODAVNICE_REQUEST = 'FETCH_PRODAVNICE_REQUEST';
export const FETCH_PRODAVNICE_SUCCESS = 'FETCH_PRODAVNICE_SUCCESS';
export const FETCH_PRODAVNICE_FAILURE = 'FETCH_PRODAVNICE_FAILURE';