export const FETCH_SVEVIJESTI_REQUEST = 'FETCH_SVEVIJESTI_REQUEST';
export const FETCH_SVEVIJESTI_SUCCESS = 'FETCH_SVEVIJESTI_SUCCESS';
export const FETCH_SVEVIJESTI_FAILURE = 'FETCH_SVEVIJESTI_FAILURE';