export const FETCH_IZVJESTAJI_SA_VOZNJE_REQUEST = 'FETCH_IZVJESTAJI_SA_VOZNJE_REQUEST';
export const FETCH_IZVJESTAJI_SA_VOZNJE_SUCCESS = 'FETCH_IZVJESTAJI_SA_VOZNJE_SUCCESS';
export const FETCH_IZVJESTAJI_SA_VOZNJE_FAILURE = 'FETCH_IZVJESTAJI_SA_VOZNJE_FAILURE';

